Alias /gpssensor /home/ubuntu/apps/m_gpssensor/current/web/dist

<Directory /home/ubuntu/apps/m_gpssensor/current/web/dist>
    Options -Indexes +FollowSymLinks
    AllowOverride None
    Require all granted
    DirectoryIndex index.html
    FallbackResource /gpssensor/index.html
</Directory>

<LocationMatch "^/gpssensor/downloads/.*\.apk$">
    ForceType application/vnd.android.package-archive
    Header set Content-Disposition "attachment; filename=GpsSensorLogger.apk"
</LocationMatch>
