RedirectMatch 301 ^/gpssensor$ /gpssensor/
Alias /gpssensor/ /var/www/gpssensor/current/

<Directory /var/www/gpssensor/current>
    Options -Indexes +FollowSymLinks
    AllowOverride None
    Require all granted
    DirectoryIndex index.html
    FallbackResource /gpssensor/index.html
</Directory>

<LocationMatch "^/gpssensor/downloads/.*\.apk$">
    ForceType application/vnd.android.package-archive
    Header set Content-Disposition "attachment; filename=GpsSensorLogger.apk"
</LocationMatch>
